

export const ACTION_CHANGE_MESSAGEFOLDER = 'ACTION_CHANGE_MESSAGEFOLDER';
export const ACTION_CHANGE_ACTIVE_CONTACT = 'ACTION_CHANGE_ACTIVE_CONTACT';
export const ACTION_CHANGE_ANSWER_FROM_CHAK = 'ACTION_CHANGE_ANSWER_FROM_CHAK';
export const ACTION_CHANGE_NEW_MESSAGE = 'ACTION_CHANGE_NEW_MESSAGE';
export const ACTION_CHANGE_TEXT_NEW_MESSAGE = 'ACTION_CHANGE_TEXT_NEW_MESSAGE';
